package com.example.myapp.core.ui.theme

import androidx.compose.ui.graphics.Color

// Premium Executive Light Theme Palette (Deep Indigo & Modern Slate)
val md_theme_light_primary = Color(0xFF2563EB) // Modern Vibrant Royal Blue
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDBEAFE) // Soft Ice Blue
val md_theme_light_onPrimaryContainer = Color(0xFF1E3A8A)
val md_theme_light_secondary = Color(0xFF475569) // Slate Gray
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF1F5F9)
val md_theme_light_onSecondaryContainer = Color(0xFF0F172A)
val md_theme_light_tertiary = Color(0xFF0D9488) // Modern Teal Accent
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCCFBF1)
val md_theme_light_onTertiaryContainer = Color(0xFF115E59)
val md_theme_light_error = Color(0xFFDC2626)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFEE2E2)
val md_theme_light_onErrorContainer = Color(0xFF991B1B)
val md_theme_light_background = Color(0xFFF8FAFC)
val md_theme_light_onBackground = Color(0xFF0F172A)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF0F172A)
val md_theme_light_surfaceVariant = Color(0xFFF1F5F9)
val md_theme_light_onSurfaceVariant = Color(0xFF64748B)
val md_theme_light_outline = Color(0xFFCBD5E1)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF8FAFC)
val md_theme_light_surfaceContainer = Color(0xFFF1F5F9)
val md_theme_light_surfaceContainerHigh = Color(0xFFE2E8F0)
val md_theme_light_surfaceContainerHighest = Color(0xFFCBD5E1)

// Premium Obsidian Dark Theme Palette (Deep OLED Obsidian & Electric Indigo)
val md_theme_dark_primary = Color(0xFF60A5FA) // Electric Blue
val md_theme_dark_onPrimary = Color(0xFF0B192C)
val md_theme_dark_primaryContainer = Color(0xFF1E40AF)
val md_theme_dark_onPrimaryContainer = Color(0xFFDBEAFE)
val md_theme_dark_secondary = Color(0xFF94A3B8)
val md_theme_dark_onSecondary = Color(0xFF0F172A)
val md_theme_dark_secondaryContainer = Color(0xFF1E293B)
val md_theme_dark_onSecondaryContainer = Color(0xFFF8FAFC)
val md_theme_dark_tertiary = Color(0xFF2DD4BF)
val md_theme_dark_onTertiary = Color(0xFF042F2E)
val md_theme_dark_tertiaryContainer = Color(0xFF115E59)
val md_theme_dark_onTertiaryContainer = Color(0xFFCCFBF1)
val md_theme_dark_error = Color(0xFFF87171)
val md_theme_dark_onError = Color(0xFF450A0A)
val md_theme_dark_errorContainer = Color(0xFF7F1D1D)
val md_theme_dark_onErrorContainer = Color(0xFFFEE2E2)
val md_theme_dark_background = Color(0xFF0B0F17) // Ultra-rich obsidian dark
val md_theme_dark_onBackground = Color(0xFFF8FAFC)
val md_theme_dark_surface = Color(0xFF111827)
val md_theme_dark_onSurface = Color(0xFFF8FAFC)
val md_theme_dark_surfaceVariant = Color(0xFF1F2937)
val md_theme_dark_onSurfaceVariant = Color(0xFF94A3B8)
val md_theme_dark_outline = Color(0xFF334155)
val md_theme_dark_surfaceContainerLowest = Color(0xFF070A0F)
val md_theme_dark_surfaceContainerLow = Color(0xFF0B0F17)
val md_theme_dark_surfaceContainer = Color(0xFF111827)
val md_theme_dark_surfaceContainerHigh = Color(0xFF1F2937)
val md_theme_dark_surfaceContainerHighest = Color(0xFF374151)
